@startuml
'https://plantuml.com/sequence-diagram

title Check-in and Check-out by vehicle QR code

autonumber

group Check-in
    Owner -> User: scan vehicle QR code for check-in
    Owner -> ParkingSystem: submit parking information
    Owner <- ParkingSystem: return vehicle information
    Owner -> ParkingSystem: Confirm check-in
end

autonumber

group Check-out
    Owner -> User: Scan vehicle QR code for check-out
    Owner -> ParkingSystem: query parking information
    Owner <- ParkingSystem: return parking information, including parking fee
    Owner -> ParkingSystem: Confirm check-out
end
@enduml